apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: dep2
  name: dep2
spec:
  replicas: 1
  selector:
    matchLabels:
      run: dep2
  template:
    metadata:
      labels:
        run: dep2
    spec:
      containers:
      - image: ipedrazas/docmock
        name: dep2
        ports:
        - containerPort: 5000
        env:
        - name: ENDPOINT
          value: "/hello"
        - name: BJSON
          value: ewogICJuYW1lIjogIkl2YW4iLAogICJBZ2UiOiA0Mgp9Cg==
        - name: DEBUG
          value: "true"
        - name: DEPENDENCIES
          value: "dep2dep2/hello,dep2dep1/hello"


---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: dep2
  name: dep2
  namespace: default
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
    name: http
  selector:
    run: dep2
  sessionAffinity: None
  type: ClusterIP
  