apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: dep3
  name: dep3
spec:
  replicas: 1
  selector:
    matchLabels:
      run: dep3
  template:
    metadata:
      labels:
        run: dep3
    spec:
      containers:
      - image: ipedrazas/docmock
        name: dep3
        ports:
        - containerPort: 5000
        env:
        - name: ENDPOINT
          value: "/"
        - name: BJSON
          value: ewogICJuYW1lIjogIkl2YW4iLAogICJBZ2UiOiA0Mgp9Cg==
        - name: DEBUG
          value: "true"


---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: dep3
  name: dep3
  namespace: default
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
    name: http
  selector:
    run: dep3
  sessionAffinity: None
  type: ClusterIP
  