apiVersion: v1
kind: Service
metadata:
  labels:
    app: istio
    heritage: Tiller
    istio: istio-mixer
  name: istio-mixer
  namespace: default
spec:
  ports:
  - name: tcp
    port: 9091
    protocol: TCP
    targetPort: 9091
  - name: configapi
    port: 9094
    protocol: TCP
    targetPort: 9094
  - name: prometheus
    port: 42422
    protocol: TCP
    targetPort: 42422
  selector:
    app: istio
    component: cc-istio-mixer
    istio: cc-istio-mixer
    release: cc
  sessionAffinity: None
  type: ClusterIP
